apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-consumer
  namespace: default
  labels:
    app: ms-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-consumer
  template:
    metadata:
      labels:
        name: ms-consumer
        app: ms-consumer
    spec:
      hostname: ms-consumer
      containers:
      - name: ms-consumer
        image: devlambertjoao/ms-consumer:1.0.9
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
        env:
        - name: KAFKA_BROKER
          value: kafka-cluster:9092
        - name: PORT
          value: '8091'
        - name: APM_SERVER
          value: apm-server:8200
        ports:
        - containerPort: 8091

---

apiVersion: v1
kind: Service
metadata:
  name: ms-consumer
  namespace: default
  labels:
    app: ms-consumer
spec:
  type: NodePort
  selector:
    app: ms-consumer
  ports:
  - name: ms-consumer
    protocol: TCP
    port: 8091
    targetPort: 8091
    nodePort: 30891