apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-producer
  namespace: default
  labels:
    app: ms-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-producer
  template:
    metadata:
      labels:
        name: ms-producer
        app: ms-producer
    spec:
      hostname: ms-producer
      containers:
      - name: ms-producer
        image: devlambertjoao/ms-producer:1.0.5
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
        env:
        - name: KAFKA_BROKER
          value: kafka-cluster:9092
        - name: PORT
          value: '8090'
        ports:
        - containerPort: 8090

---

apiVersion: v1
kind: Service
metadata:
  name: ms-producer
  namespace: default
  labels:
    app: ms-producer
spec:
  type: NodePort
  selector:
    app: ms-producer
  ports:
  - name: ms-producer
    protocol: TCP
    port: 8090
    targetPort: 8090
    nodePort: 30890