apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-web
  namespace: default
  labels:
    app: ms-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-web
  template:
    metadata:
      labels:
        name: ms-web
        app: ms-web
    spec:
      hostname: ms-web
      containers:
      - name: ms-web
        image: devlambertjoao/ms-web:1.1.14
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ms-web
  namespace: default
  labels:
    app: ms-web
spec:
  type: NodePort
  selector:
    app: ms-web
  ports:
  - name: ms-web
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30895